disabled_rules:

- comment_spacing
- array_init
- attributes
- explicit_type_interface
- conditional_returns_on_newline
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_enum_arguments
- expiring_todo
- explicit_acl
- explicit_top_level_acl
- explicit_self
- explicit_enum_raw_value
- raw_value_for_camel_cased_codable_enum
- legacy_hashing
- missing_docs
- nimble_operator
- no_extension_access_modifier
- no_fallthrough_only
- notification_center_detachment
- nslocalizedstring_key
- nslocalizedstring_require_bundle
- nsobject_prefer_isequal
- object_literal
- no_grouping_extension
- prefixed_toplevel_constant
- prohibited_interface_builder
- required_deinit
- required_enum_case
- strong_iboutlet
- trailing_whitespace
- vertical_whitespace_opening_braces
- file_header
- trailing_closure
- multiline_arguments_brackets
- multiline_function_chains
- vertical_whitespace_between_cases
- cyclomatic_complexity
- sorted_imports
- weak_delegate
- closure_end_indentation
- colon
- implicit_return
- optional_data_string_conversion
- redundant_discardable_let

opt_in_rules:
- joined_default_parameter
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_body_length
- closure_parameter_position
- closure_spacing
- collection_alignment
- comma
- compiler_protocol_init
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- convenience_type
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- duplicate_imports
- duplicate_enum_cases
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- extension_access_modifier
- explicit_init
- file_types_order
- fallthrough
- fatal_error_message
- file_length
- file_name
- first_where
- flatmap_over_map_reduce
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_default_parameter_at_end
- function_parameter_count
- generic_type_name
- identical_operands
- identifier_name
- implicit_getter
- implicitly_unwrapped_optional
- is_disjoint
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- lower_acl_than_parent
- legacy_multiple
- mark
- multiline_parameters
- multiline_arguments
- multiline_literal_brackets
- multiline_parameters_brackets
- multiple_closures_with_trailing_closure
- modifier_order
- no_space_in_method_call
- number_separator
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- reduce_boolean
- reduce_into
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_set_access_control
- redundant_type_annotation
- redundant_string_enum_value
- redundant_optional_initialization
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- statement_position
- static_operator
- strict_fileprivate
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- toggle_bool
- trailing_newline
- type_body_length
- trailing_semicolon
- type_name

- unavailable_function
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unused_enumerated
- unowned_variable_capture
- untyped_error_in_catch
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- vertical_whitespace_closing_braces
- void_return
- xct_specific_matcher
- xctfail_message
- yoda_condition

analyzer_rules:
- unused_declaration
- unused_import

closure_spacing:
  severity: error

force_unwrapping:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

control_statement:
  severity: error

explicit_init:
  severity: error

file_length:
  warning: 800
  error: 800

first_where:
  severity: error

function_body_length:
  warning: 50
  error: 50

function_parameter_count:
  warning: 8
  error: 8

generic_type_name:
    min_length:
        warning: 1
        error: 1
    max_length:
        warning: 30
        error: 30

identifier_name:
    min_length:
        warning: 1
        error: 1
    max_length:
        warning: 80
        error: 80

large_tuple:
  warning: 4
  error: 4

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_nsgeometry_functions:
  severity: error

line_length:
   warning: 140
   error: 160

mark:
  severity: error

nesting:
  type_level: 1
  function_level: 2

number_separator:
  severity: error

opening_brace:
  severity: error

operator_whitespace:
  severity: error

operator_usage_whitespace:
  severity: error

overridden_super_call:
  severity: error

private_outlet:
  severity: error

private_unit_test:
  severity: error

prohibited_super_call:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

shorthand_operator:
  severity: error

statement_position:
  statement_mode: default

  severity: error

switch_case_on_newline:
  severity: error

syntactic_sugar:
  severity: error

todo:
  severity: error
  only: FIXME

trailing_comma:
  mandatory_comma: true
  severity: error

trailing_newline:
  severity: error

trailing_semicolon:
  severity: error

type_body_length:
  warning: 400
  error: 400

type_name:
    min_length:
        warning: 0
        error: 3
    max_length:
        warning: 80
        error: 80

unused_closure_parameter:
  severity: error

unused_enumerated:
  severity: error

unused_optional_binding:
  severity: error

valid_ibinspectable:
  severity: error

vertical_parameter_alignment:
  severity: error

vertical_whitespace:
  severity: error

file_name:
  excluded: ["main.swift", "*Asset.swift"]

reporter: "xcode"
